sudo: required
dist: bionic
language: java

jdk:
  - openjdk8

services:
  - xvfb
  
addons:
    chrome: stable
    

  
before_install:
- sudo apt-get update
- sudo apt-get install dbus-x11
- export DISPLAY=:99.0

   
install:
    mvn install 















